name: agro_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  flutter_date_pickers: ^0.4.3
  device_info_plus: ^11.4.0
  fl_chart: 0.50.1
  month_picker_dialog: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
